require_relative '../lib/aws_cost_service'
require_relative '../lib/slack_client'
require 'date'
require 'json'

class CostNotification
  def initialize
    @cost_service = AwsCostService.new
    @slack_client = SlackClient.new
  end

  def execute(date = Date.today - 1)
    # 昨日の料金を取得
    daily_cost = @cost_service.get_daily_cost(date)

    # 今月の累計料金を取得
    monthly_total = @cost_service.get_monthly_cost(Date.today)

    # Slackメッセージを作成して送信
    message = build_slack_message(date, daily_cost[:total], monthly_total, daily_cost[:services])
    @slack_client.send_message(message)

    {
      daily_total: daily_cost[:total],
      monthly_total: monthly_total,
      services: daily_cost[:services]
    }
  end

  private

  def build_slack_message(date, daily_total, monthly_total, service_costs)
    # 上位5サービスのみ表示
    top_services = service_costs.take(5)

    services_text = top_services.map do |item|
      "• #{item[:service]}: $#{sprintf('%.2f', item[:cost])}"
    end.join("\n")

    {
      text: "AWS Daily Cost Report - #{date.strftime('%Y-%m-%d')}",
      blocks: [
        {
          type: "header",
          text: {
            type: "plain_text",
            text: "💰 AWS Daily Cost Report"
          }
        },
        {
          type: "section",
          fields: [
            {
              type: "mrkdwn",
              text: "*Date:*\n#{date.strftime('%Y-%m-%d')}"
            },
            {
              type: "mrkdwn",
              text: "*Daily Cost:*\n$#{sprintf('%.2f', daily_total)}"
            },
            {
              type: "mrkdwn",
              text: "*Monthly Total:*\n$#{sprintf('%.2f', monthly_total)}"
            },
            {
              type: "mrkdwn",
              text: "*Currency:*\nUSD"
            }
          ]
        },
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: "*Top Services (Yesterday):*\n#{services_text}"
          }
        },
        {
          type: "divider"
        },
        {
          type: "context",
          elements: [
            {
              type: "mrkdwn",
              text: "Generated by AWS Cost Notification Lambda"
            }
          ]
        }
      ]
    }
  end
end
